### PR TITLE
Fix supported storage types by adding 'apcng' to allowed values

### PR DESCRIPTION
**Pull request by edditor**
bug of https://github.com/artprima/prometheus-metrics-bundle/commit/150b9c71ccd5ee7303444a69fd06c86a5c516064

### CODE REVIEW

**Comment by Johnmeurt** [comment]
It seems the bug you noticed is in the README
```
 apcung  Prometheus\Storage\APCng    
```
The drive name is apcng.

Your PR changes a deprecated section of the configuration. Your config file should  now use the storage key:
```yaml
storage:
        # Known values: in_memory, apcu, apcng, redis
        type: apcng
```

**Comment by Johnmeurt** [comment]
You are trying to add support of an adapter in a deprecated section.
Did you try to change your configuration file to 

```yaml
# Type key is deprecated. Remove this key and try to add the storage section
#type: apcng

# v1.14 add the section storage.
storage:
        # Known values: in_memory, apcu, apcng, redis
        type: apcng
```
Does this change suit you ?
The validation by choice list has been removed on `storage.type`.

**Comment by edditor** [comment]
Sorry, I didn't see that the configuration keys had changed. Thank you, this works for me, so I think it no longer needs to be added to the allowed values in the deprecated config section.

**Comment by Johnmeurt** [comment]
You could let the PR open in case @denisvmedia wants to add support of the apcng storage on the old configuration synthax.
In case not the README file should be fix.

**Review by denisvmedia — APPROVED** [review]

**Comment by denisvmedia** [comment]
Thank you @edditor and @Johnmeurt. Merging.

**Pull request merged**
