### PR TITLE
Replace prometheus client PHP.

### PR DESCRIPTION
**Pull request by jb-reynaud**
## Why
The prometheus client PHP is not maintained anymore, as it was disccused in [this issue](https://github.com/endclothing/prometheus_client_php/issues/56).

It was locked to guzzle 6, and now thanks to @LKaemmerling Guzzle is not required anymore (or at least it's used in dev, with Guzzle 7).

## How
Replace endclothing's dependance by promPHP's one.

### CODE REVIEW

**Comment by LKaemmerling** [comment]
Hey @jb-reynaud, great think :) For the maintainers of this project:
 - This Prometheus library will be maintained in the future. We decided to move it into an "open" organization so that it won't rely on a company for maintenance (like before).

The failing test is somehow expected. With the latest release, we always add "default" metrics, like the PHP version (future wise there is more planned). You can (but i won't recommend it) disable the default metrics by simply passing false to the `CollectorRegistry` [constructor](https://github.com/PromPHP/prometheus_client_php/blob/master/src/Prometheus/CollectorRegistry.php#L50).

[Sample within our tests](https://github.com/PromPHP/prometheus_client_php/blob/master/tests/Test/Prometheus/AbstractCollectorRegistryTest.php#L55)

**Comment by denisvmedia** [comment]
@jb-reynaud thank you for your PR. Would you mind to fix the failing test so that we could merge it? This is the failing line: https://github.com/artprima/prometheus-metrics-bundle/blob/749857072d9c60d8a387a80b79da7c24cee9c151/Tests/Metrics/AppMetricsTest.php#L64

**Comment by jb-reynaud** [comment]
I've updated and cleaned the test

**Comment by denisvmedia** [comment]
Thank you!

**Pull request merged**
