### PR TITLE
Collect status code in label

### PR DESCRIPTION
**Pull request by L3tum**
Hey, thanks for this library!

This is a small change that would really go a long way IMO. 

While it's already good to know whether a request was successful (2xx/3xx) or failed (4xx/5xx), it would be better to be able to distinguish why it failed. E.g. a 404 is dramatically different from a 401 or 403.

### CODE REVIEW

**Comment by L3tum** [comment]
I'm not sure why the integration tests are failing (I can't even find them in the repo)

**Comment by denisvmedia** [comment]
Not only integration tests are broken, unit tests are broken as well.
You can find integration tests pipeline here: https://github.com/artprima/prometheus-metrics-bundle/blob/master/.github/workflows/symfony.yml

Also, could you please set `develop` branch as a destination of your MR? Thank you.

**Comment by L3tum** [comment]
The tests appear to be all fixed now. One thing I do not know is how you want to handle the `all` "action" and whether the status should be "all" as well, like it is now, or if there should be an additional `null` check.

I doubt the status can ever actually be null, but I wanted to stay consistent with the rest of the code.

**Comment by denisvmedia** [comment]
Hi @L3tum . I decided to not merge this MR. It appears so that it may have undesired consequences in projects that use this library. But I have a solution that should work for you:

```yaml
artprima_prometheus_metrics:
    disable_default_metrics: true
```

By doing this, you can effectively disable the default metrics and use your own solution in your project.

**Pull request closed without merging**
